#!/usr/bin/env python3
"""Visualize logged Dynamixel motor temperatures."""

import argparse
from pathlib import Path
from typing import Optional


def plot_temperature_log(
    log_path: Path,
    output_path: Optional[Path],
    show_plot: bool,
    max_points: int = 5000,
    y_min: Optional[float] = None,
    y_max: Optional[float] = None,
):
    """Plot all motor temperatures from a CSV log."""
    log_path = Path(log_path)
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")

    try:
        import pandas as pd
        import matplotlib.pyplot as plt
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise ImportError(
            "Plotting requires pandas and matplotlib to be installed."
        ) from exc

    df = pd.read_csv(log_path)
    if df.empty:
        raise ValueError("Log file is empty.")
    def is_motor_temp(col: str) -> bool:
        if not (col.startswith("m") and col.endswith("_temp_c")):
            return False
        motor_id_part = col[len("m") : -len("_temp_c")]
        return motor_id_part.isdigit()

    motor_cols = [col for col in df.columns if is_motor_temp(col)]
    if not motor_cols:
        raise ValueError("No motor temperature columns found in log.")

    # Convert motor columns to numeric and drop rows where all motor values are NaN
    for col in motor_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.dropna(subset=motor_cols, how="all").reset_index(drop=True)
    if df.empty:
        raise ValueError("No valid motor temperature data found after cleaning.")

    if "elapsed_sec" in df.columns:
        elapsed_sec = pd.to_numeric(df["elapsed_sec"], errors="coerce")
        if elapsed_sec.isna().all():
            x_values = pd.to_datetime(df["timestamp"])
            x_label = "Timestamp"
        else:
            x_values = elapsed_sec / 3600.0
            x_label = "Elapsed time (hours)"
    else:
        x_values = pd.to_datetime(df["timestamp"])
        x_label = "Timestamp"

    if len(df) > max_points:
        step = max(1, len(df) // max_points)
        df = df.iloc[::step].reset_index(drop=True)
        if isinstance(x_values, pd.Series):
            x_values = x_values.iloc[::step].reset_index(drop=True)
        else:
            x_values = x_values[::step]

    fig, ax = plt.subplots(figsize=(12, 6))
    color_cycle = plt.get_cmap("tab20")
    for idx, col in enumerate(motor_cols):
        color = color_cycle(idx % color_cycle.N)
        values = df[col]
        ax.plot(x_values, values, label=col, color=color)

    ax.set_xlabel(x_label, labelpad=10)
    ax.set_ylabel("Temperature (deg C)")
    ax.set_title(f"Motor temperature log ({log_path.name})")
    ax.grid(alpha=0.3)
    if y_min is not None or y_max is not None:
        ax.set_ylim(bottom=y_min, top=y_max)
    legend = ax.legend(ncol=4, fontsize=8)
    fig.tight_layout(rect=[0, 0.08, 1, 1])
    if legend:
        legend.set_bbox_to_anchor((0.5, -0.12))
        legend.set_loc("upper center")

    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(output_path, bbox_inches="tight")
        print(f"[plot] Saved plot to {output_path}")

    if show_plot:
        plt.show()
    else:
        plt.close(fig)


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Plot motor temperatures recorded by monitor_motor_temperatures.py."
        )
    )
    parser.add_argument(
        "log_path",
        type=Path,
        help="CSV log generated by monitor_motor_temperatures.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to save the rendered plot.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the plot window (requires GUI support).",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=5000,
        help="Maximum number of points to plot (data will be downsampled if larger).",
    )
    parser.add_argument(
        "--y-min",
        type=float,
        default=None,
        help="Optional lower bound for temperature axis.",
    )
    parser.add_argument(
        "--y-max",
        type=float,
        default=None,
        help="Optional upper bound for temperature axis.",
    )
    args = parser.parse_args()

    plot_temperature_log(
        log_path=args.log_path,
        output_path=args.output,
        show_plot=args.show,
        max_points=args.max_points,
        y_min=args.y_min,
        y_max=args.y_max,
    )


if __name__ == "__main__":
    main()
